version: '3.5'

services:

    www:
        image: nginx:1.18.0-alpine
        container_name: www
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ../src:/var/www/html

    db:
        image: mysql:5.7.23
        container_name: db
        env_file: .env
        volumes:
            - db-data:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    php:
        build: ./docker/php
        image: php55:latest
        container_name: php
        depends_on:
            - db
        # user: "1000:1000"
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ../src:/var/www/html
            - ./docker/php/usr/local/etc/php/conf.d/add-php.ini:/usr/local/etc/php/conf.d/add-php.ini
            - ./docker/php/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    ci:
       image: jenkins/jenkins:lts
       container_name: ci
       ports:
           - 18080:8080
       environment:
           - JAVA_OPTS="-Xmx1g"
       volumes:
           - jenkins-data:/var/jenkins_home

    adminer:
        image: adminer:latest
        container_name: adminer
        ports:
            - 8080:8080

volumes:
    db-data:
    jenkins-data:
